### ISSUE TITLE
Should progs depend on all

### ISSUE THREAD

**Issue by andreww** [anowacki/seismo-fortran#3]
For a clean build, `make progs` fails because the object files and modules have not been compiled ahead of the attempt to build the programmes. Should `all` be a dependancy for `progs` to allow `make progs` to work?

**Comment by anowacki** [comment]
Yes it should!  The Makefiles are a bit shoddy and probably the whole repo can be sensibly reorganised.  So please feel free to reorganise, so long as the libraries stay in `lib/`, Fortran headers in `mods/` and programs in `progs/bin/`.

**Comment by andreww** [comment]
This is fixed.
